<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="36942" started-at="2019-08-04T10:04:21Z" finished-at="2019-08-04T10:04:58Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="36942" started-at="2019-08-04T10:04:21Z" finished-at="2019-08-04T10:04:58Z">
      <class name="testScripts.Oneway">
        <test-method status="PASS" signature="onepersoneway()[pri:0, instance:testScripts.Oneway@19e13df]" name="onepersoneway" duration-ms="8295" started-at="2019-08-04T15:34:30Z" finished-at="2019-08-04T15:34:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- onepersoneway -->
        <test-method status="PASS" signature="SetStatus()[pri:0, instance:testScripts.Oneway@19e13df]" name="SetStatus" is-config="true" duration-ms="4716" started-at="2019-08-04T15:34:54Z" finished-at="2019-08-04T15:34:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetStatus -->
      </class> <!-- testScripts.Oneway -->
      <class name="logicTest.dataproviderconcept">
        <test-method status="SKIP" signature="loginTest(java.lang.String, java.lang.String)[pri:0, instance:logicTest.dataproviderconcept@15530b9]" name="loginTest" duration-ms="0" started-at="2019-08-04T15:34:54Z" data-provider="getdata2" finished-at="2019-08-04T15:34:54Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void logicTest.dataproviderconcept.loginTest(java.lang.String,java.lang.String) requires a @DataProvider named : getdata2]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void logicTest.dataproviderconcept.loginTest(java.lang.String,java.lang.String) requires a @DataProvider named : getdata2
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- logicTest.dataproviderconcept -->
      <class name="testScripts.Twoway">
        <test-method status="PASS" signature="Twopersoneway()[pri:0, instance:testScripts.Twoway@198378d]" name="Twopersoneway" duration-ms="7659" started-at="2019-08-04T15:34:38Z" finished-at="2019-08-04T15:34:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Twopersoneway -->
        <test-method status="PASS" signature="Twopersontwoway()[pri:0, instance:testScripts.Twoway@198378d]" name="Twopersontwoway" duration-ms="7403" started-at="2019-08-04T15:34:46Z" finished-at="2019-08-04T15:34:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Twopersontwoway -->
      </class> <!-- testScripts.Twoway -->
      <class name="testScripts.loginTest">
        <test-method status="PASS" signature="launch()[pri:0, instance:testScripts.loginTest@cb5822]" name="launch" is-config="true" duration-ms="11465" started-at="2019-08-04T15:34:10Z" finished-at="2019-08-04T15:34:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method status="PASS" signature="logintest(java.lang.String, java.lang.String)[pri:0, instance:testScripts.loginTest@cb5822]" name="logintest" duration-ms="7881" started-at="2019-08-04T15:34:22Z" data-provider="getdata2" finished-at="2019-08-04T15:34:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[mercury]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="quitbrowser()[pri:0, instance:testScripts.loginTest@cb5822]" name="quitbrowser" is-config="true" duration-ms="3609" started-at="2019-08-04T15:34:58Z" finished-at="2019-08-04T15:35:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitbrowser -->
      </class> <!-- testScripts.loginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
